### ISSUE TITLE
Mandatory tax miners

### ISSUE THREAD

**Issue by Sepkuh** [kulupu/kulupu#105]
If I wanted to propose a change from voluntary tax to mandatory tax for miners. Is it doable with a proposal?  So people can vote democratically.  If so?  Could you maybe explain or help me how to do so? Since I have never done that and have no clue how it works. Thanks
.

**Comment by Kaos0ne** [comment]
A mandatory taxation would be interesting, obviously by vote, let's see if Wei will answer you, _voluntarily_.
