### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'supplied instant is later than self', library/std/src/time.rs:271

### ISSUE THREAD

**Issue by arbreton** [kulupu/kulupu#114]
Version: 2.4.0-7dd40ad-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/std/src/panicking.rs:573:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/std/src/panicking.rs:476:9
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/std/src/sys_common/backtrace.rs:153:18
   4: rust_begin_unwind
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/std/src/panicking.rs:475:5
   5: core::panicking::panic_fmt
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/core/src/panicking.rs:85:14
   6: core::option::expect_failed
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/core/src/option.rs:1213:5
   7: core::option::Option<T>::expect
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/core/src/option.rs:333:21
      std::time::Instant::duration_since
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/std/src/time.rs:271:9
      <std::time::Instant as core::ops::arith::Sub>::sub
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/std/src/time.rs:396:9
      std::time::Instant::elapsed
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/std/src/time.rs:335:9
   8: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::usage_info
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  11: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  14: tokio::runtime::task::core::Core<T,S>::poll
  15: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  16: tokio::runtime::task::harness::Harness<T,S>::poll
  17: std::thread::local::LocalKey<T>::with
  18: tokio::runtime::thread_pool::worker::Context::run_task
  19: tokio::runtime::thread_pool::worker::Context::run
  20: tokio::macros::scoped_tls::ScopedKey<T>::set
  21: tokio::runtime::thread_pool::worker::run
  22: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  24: tokio::runtime::task::raw::poll
  25: tokio::runtime::blocking::pool::Inner::run
  26: tokio::runtime::context::enter
  27: std::sys_common::backtrace::__rust_begin_short_backtrace
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}
  29: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/663d2f5cd3163f17eddb74ee1e028d542255f21a/library/std/src/sys/unix/thread.rs:87:17
  30: start_thread
  31: clone

Thread 'tokio-runtime-worker' panicked at 'supplied instant is later than self', library/std/src/time.rs:271

This is a bug. Please report it at:

	https://github.com/kulupu/kulupu/issues

**Comment by sorpaas** [comment]
Make sure system time is synced and the issue should resolve.
