### ISSUE TITLE
POW verifier's verify not executed

### ISSUE THREAD

**Issue by alanpoon** [kulupu/kulupu#16]
Hi, this function is not executed [substrate pow import_queue](https://github.com/paritytech/substrate/blob/4ed0ad6fbd8b25b63105dc21710ace3c329de0d1/client/consensus/pow/src/lib.rs#L333)
even if it is used (here)[https://github.com/kulupu/kulupu/blob/master/src/service.rs#L102]. Is it because I am running as cargo run -- --dev --validator and there is only one node, no need to verify?

**Comment by sorpaas** [comment]
@alanpoon The queue handles incoming blocks from network peers. If you're only producing blocks locally but not actually connecting to the network, the the function is indeed not executed.

If you're running Kulupu, please check if you're able to connect to peers. If not, it may be a bug and let me know!

**Comment by alanpoon** [comment]
If I put computation intensive code in the compute function, won't it take the same amount of computation time for verification between the peers?

**Comment by alanpoon** [comment]
If I put computation intensive code in the compute function, won't it take the same amount of computation time for verification between the peers?
