### ISSUE TITLE
build faild.

### ISSUE THREAD

**Issue by yunzck8s** [kulupu/kulupu#166]
error: failed to run custom build command for `kulupu-randomx-sys v2.8.1 (/rustbuilder/kulupu/pow/randomx/sys)`

Caused by:
  process didn't exit successfully: `/rustbuilder/kulupu/target/release/build/kulupu-randomx-sys-f93c0d6f2d8e4900/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=RANDOMX_ARCH
  running: "cmake" "/rustbuilder/kulupu/pow/randomx/sys/randomx" "-DARCH=default" "-DCMAKE_INSTALL_PREFIX=/rustbuilder/kulupu/target/release/build/kulupu-randomx-sys-07173c431f00a5b7/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"

  --- stderr
  CMake Error: The source directory "/rustbuilder/kulupu/pow/randomx/sys/randomx" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /rustbuilder/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.45/src/lib.rs:894:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by aiyajsupra** [comment]
@yunzck8s 
Clone all source from https://github.com/tevador/RandomX to pow/randomx/sys/randomx.

**Comment by sorpaas** [comment]
The canonical way is to run `git submodule update --init --recursive`.
