### ISSUE TITLE
Parity Signer support

### ISSUE THREAD

**Issue by emielvanderhoek** [kulupu/kulupu#18]
On first try Parity Signer does not yet seem to work (as external signer) via Polkadot JS Apps.

**Comment by sorpaas** [comment]
Will be fixed by https://github.com/paritytech/parity-signer/pull/612

**Comment by hanwencheng** [comment]
Android app could be downloaded here: https://github.com/paritytech/parity-signer/releases/tag/v4.2.3-beta
