### ISSUE TITLE
Incorrect Time in Polkadot JS Apps

### ISSUE THREAD

**Issue by emielvanderhoek** [kulupu/kulupu#19]
Incorrect Time in Polkadot JS Apps
Time is calculated with 6s blocktime (not 60s blocktime)

![image](https://user-images.githubusercontent.com/14069142/81324538-68be8800-9097-11ea-9fc2-4a3bba9191ed.png)

**Comment by emielvanderhoek** [comment]
@sorpaas 
In Polkadot/Kulupu there is a constant: `babe`.`expectedBlockTime`.
Kulupu does not use `Babe` for block production. 
I'd suggest to introduce a runtime constant in the Kulupu runtime with a 60 (second) value.

![afbeelding](https://user-images.githubusercontent.com/14069142/89131956-f4b64380-d510-11ea-96e9-61ba344ae743.png)

**Comment by jacogr** [comment]
Fixed in https://github.com/polkadot-js/apps/pull/3448
