### ISSUE TITLE
Is it possible to add grandpa finality to this chain?

### ISSUE THREAD

**Issue by kaichaosun** [kulupu/kulupu#28]
I was learned that transaction of a PoW chain is not guaranteed deterministic, but holds a probabilistic finality.
Substrate use Babe to propose blocks as default. So I'm wondering whether it's make sense to combine PoW (to propose block) and Grandpa (to finalize the block, the sets to vote on Grandpa can be elected somehow) or not.
It may sound dump, but it can be beautiful since we get the permissionless of PoW, also guarantee enough security.

**Comment by sorpaas** [comment]
Yeah hybrid is definitely possible and I remember someone had already tried that. We'll also have to add staking support to support a dynamic validator set of GRANDPA.

**Comment by kaichaosun** [comment]
Sounds great, feel free to close this issue if it's not something will happen on Kulupu network. @sorpaas

**Comment by sorpaas** [comment]
Pure PoW vs hybrid PoW-PoS is still under discussions. But since the question of this issue is already answered. Let me close this.
