### ISSUE TITLE
Expose Payment RPC Group

### ISSUE THREAD

**Issue by emielvanderhoek** [kulupu/kulupu#39]
Expose Payment RPC Group to get Multisig pallet working in Polkadot JS Apps.

![afbeelding](https://user-images.githubusercontent.com/14069142/89742647-e087be80-da9b-11ea-8675-29cb26ee1cf9.png)

**Comment by sorpaas** [comment]
To be fixed in v1.4.0.

**Comment by sorpaas** [comment]
v1.4.0 is released.
