### ISSUE TITLE
Feature Request: Log mining stats

### ISSUE THREAD

**Issue by carumusan** [kulupu/kulupu#4]
Currently it's difficult to determine the status of the miner when running. Useful information to have logged out when running:

- Number of hashes/second
- Expected time to produce block
- Predicted percentage of total hashrate
- Hashrate distribution between nodes

**Comment by Incrediblez7** [comment]
Agree. Also, please add the current difficulty of the network.

**Comment by sorpaas** [comment]
Already implemented.
