### ISSUE TITLE
v1.4.0 Compiling error's

### ISSUE THREAD

**Issue by organicuz** [kulupu/kulupu#46]
error[E0583]: file not found for module `rpc`
  --> src/main.rs:27:1
   |
27 | mod rpc;
   | ^^^^^^^^
   |
   = help: to create the module `rpc`, create file "src/rpc.rs"

error[E0422]: cannot find struct, variant or union type `FullDeps` in module `crate::rpc`
   --> src/service.rs:184:27
    |
184 |             let deps = crate::rpc::FullDeps {
    |                                    ^^^^^^^^ not found in `crate::rpc`

error[E0425]: cannot find function `create_full` in module `crate::rpc`
   --> src/service.rs:190:16
    |
190 |             crate::rpc::create_full(deps)
    |                         ^^^^^^^^^^^ not found in `crate::rpc`

error[E0277]: the size for values of type `dyn sc_service::builder::RpcExtensionBuilder<Output = _> + std::marker::Send` cannot be known at compilation time
   --> src/service.rs:183:3
    |
183 |         Box::new(move |deny_unsafe| {
    |         ^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `dyn sc_service::builder::RpcExtensionBuilder<Output = _> + std::marker::Send`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: required by `std::boxed::Box::<T>::new`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0277, E0422, E0425, E0583.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `kulupu`.

**Comment by sorpaas** [comment]
Fixed. Please re-pull v1.4.0. Sorry about this!
