### ISSUE TITLE
Why whitelist in anyupgrade?

### ISSUE THREAD

**Issue by JoshOrndorff** [kulupu/kulupu#5]
The entire [`impl<T:Trait> Module<T>` block](https://github.com/kulupu/kulupu/blob/84437c66f9c218c91e1f07de1355a343172102a1/anyupgrade/src/lib.rs#L68-L98) of `anyupgrade` is about a whitelist and checking it to know whether an inherent is needed. But it seems that code is never called.

**Comment by sorpaas** [comment]
@JoshOrndorff The code is called here: https://github.com/kulupu/kulupu/blob/84437c66f9c218c91e1f07de1355a343172102a1/runtime/src/lib.rs#L279-L311

The reason for the whitelist is that it allows each client to control whether it accepts a hard fork or not. For a sufficiently old hard fork, the whiltelist can be removed with `check_from` number advancing. If work from PoW can be trusted, then clients can just choose to follow the longest chain, regardless of whether a hard fork happens.
