### ISSUE TITLE
Windows import key does not recognize author

### ISSUE THREAD

**Issue by Swader** [kulupu/kulupu#53]
On Windows the key import for mining does not seem to work. Steps to repro:

- get Kulupu
- import any seed phrase using `import-mining-key`
- use the public key given by this command in the mining command, e.g. `./kulupu.exe --pruning=archive --validator --author PUBKEY...`
- notice the error message `ERROR sc_consensus_pow  Mining block failed with Other("Unable to mine: fetch pair from author failed")`

Using `generate-mining-key` to generate a new key and use that does not help either. Reproducible in cmd, cmder, git bash.

**Comment by shawntabrizi** [comment]
This seems like the root of the issue then. I will check when I am home the behavior of using a non default folder

**Comment by Swader** [comment]
Works if you provide the base path during import of key too, not just during mining. Otherwise it imports the key into the default location, and you're mining in another.

**Comment by gbt1988** [comment]
> Works if you provide the base path during import of key too, not just during mining. Otherwise it imports the key into the default location, and you're mining in another.

Can you paste your operation history here? What's the CLI to proivide base path ?

**Comment by Swader** [comment]
```
./kulupu --base-path some/folder/location
```

**Comment by gbt1988** [comment]
> ```
> ./kulupu --base-path some/folder/location
> ```

I'm sorry ,i'm not getting you well. which location?
and Does the program set a  default base-path?

**Comment by Swader** [comment]
Whichever location you want. That's a custom location into which you want to save Kulupu data. Doesn't matter where you put it. The program does have a default, yes, though I don't know which default it is off the top of my head.

The only thing that matters here is that you give the import key command and the kulupu binary the same base path.
