### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jian19930605** [kulupu/kulupu#58]
ERROR sc_consensus_pow  Mining block failed with Other("Unable to mine: fetch pair from author failed"). Sleep for 1 second before restarting...   is it normal?

**Comment by Incrediblez7** [comment]
well i got this:
`Unable to mine: pre-digest not set`

**Comment by Incrediblez7** [comment]
solved:
do `./kulupu import-mining-key -d <dir> <suri>`
suri = your "Secret seed"

**Comment by jian19930605** [comment]
dis is what? floder?

**Comment by Incrediblez7** [comment]
Dir是你放区块链数据的文件，如果没用过就不需要
在 2020年8月28日 +0800 AM10:38，jian19930605 <notifications@github.com>，写道：

**Comment by sorpaas** [comment]
Duplicate. Please use thread #70.
