### ISSUE TITLE
can't compile on linux or mac - rustc rustc 1.40.0-nightly (c553e8e88 2019-10-30)

### ISSUE THREAD

**Issue by johanneshahn** [kulupu/kulupu#6]
thread 'rustc' panicked at 'Tried to access field 0 of union with 0 fields', src/librustc_target/abi/mod.rs:742:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (c553e8e88 2019-10-30) running on x86_64-apple-darwin

note: compiler flags: -C opt-level=3 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: could not compile `kulupu`.

**Comment by sorpaas** [comment]
Should have been fixed now with newest rust and Kulupu master.
