### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by BugBang** [kulupu/kulupu#60]
error: failed to run custom build command for `kulupu-randomx-sys v2.0.0 (D:\Mining\kulupu\kulupu\pow\randomx\sys)`

Caused by:
  process didn't exit successfully: `D:\Mining\kulupu\kulupu\target\release\build\kulupu-randomx-sys-1a0ad2c3ae32aa25\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.44\src\lib.rs:885:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...

WINDOWNS10

**Comment by BugBang** [comment]
run  cargo run --release -- generate-mining-key

error: failed to run custom build command for `kulupu-randomx-sys v2.0.0 (D:\Mining\kulupu\kulupu\pow\randomx\sys)`

Caused by:
  process didn't exit successfully: `D:\Mining\kulupu\kulupu\target\release\build\kulupu-randomx-sys-1a0ad2c3ae32aa25\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.44\src\lib.rs:885:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by sorpaas** [comment]
It's a known issue that in Windows, the randomx binary is hard to build. You need to either manually find the correct llvm binary (like it's done in CI) or use the prebuilt binary.

If it's available to you, it's recommended that you use WSL or a virtual machine.
