### ISSUE TITLE
Unable to min

### ISSUE THREAD

**Issue by chywhy** [kulupu/kulupu#63]
`./kulupu --validator --author 025d4411d87aa45c7451a51c29b481f0518b51e25a0b496e656088905129fc4c --base-path db2 --unsafe-ws-external --unsafe-rpc-external --rpc-cors=all --rpc-methods=Unsafe --ws-port 9944`

ERROR sc_consensus_pow  Mining block failed with Other("Unable to mine: fetch pair from author failed"). Sleep for 1 second before restarting...

**Comment by tyleryu** [comment]
2020-08-29 22:47:05.511  ERROR sc_consensus_pow  Mining block failed with Other("Unable to mine: fetch pair from author failed"). Sleep for 1 second before restarting...
I have the same error , who can help, many thanks!

**Comment by shawntabrizi** [comment]
Please follow the instructions here: https://kulupu.network/guide/mining/

You need to generate or import a mining key for your node, and then you will be able to mine with that key.

**Comment by sorpaas** [comment]
Duplicate. Please use issue #70.
