### ISSUE TITLE
 Compiling failure

### ISSUE THREAD

**Issue by oiuacc** [kulupu/kulupu#64]
Compiling sp-storage v2.0.0-rc6 (/root/kulupu/vendor/substrate/primitives/storage)
error: failed to run custom build command for `kulupu-randomx-sys v2.1.0 (/root/kulupu/pow/randomx/sys)`

Caused by:
  process didn't exit successfully: `/root/kulupu/target/release/build/kulupu-randomx-sys-94403d178f588f57/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=RANDOMX_ARCH
  running: "cmake" "/root/kulupu/pow/randomx/sys/randomx" "-DARCH=native" "-DCMAKE_INSTALL_PREFIX=/root/kulupu/target/release/build/kulupu-randomx-sys-a68882c63d57101a/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
  -- The C compiler identification is GNU 4.8.5
  -- The CXX compiler identification is GNU 4.8.5
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Performing Test _march=native_cxx
  -- Performing Test _march=native_cxx - Success
  -- Setting CXX flag -march=native
  -- Performing Test _march=native_c
  -- Performing Test _march=native_c - Success
  -- Setting C flag -march=native
  -- Looking for include file pthread.h
  -- Looking for include file pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Performing Test HAVE_CXX_ATOMICS
  -- Performing Test HAVE_CXX_ATOMICS - Failed
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /root/kulupu/target/release/build/kulupu-randomx-sys-a68882c63d57101a/out/build
  running: "cmake" "--build" "." "--target" "all" "--config" "Release" "--"
  Scanning dependencies of target randomx
  [  3%] Building CXX object CMakeFiles/randomx.dir/src/aes_hash.cpp.o
  In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                   from /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:31,
                   from /root/kulupu/pow/randomx/sys/randomx/src/soft_aes.h:32,
                   from /root/kulupu/pow/randomx/sys/randomx/src/aes_hash.cpp:29:
  /usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
   #error This file requires compiler and library support for the \
    ^
  In file included from /root/kulupu/pow/randomx/sys/randomx/src/soft_aes.h:32:0,
                   from /root/kulupu/pow/randomx/sys/randomx/src/aes_hash.cpp:29:
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:34:1: error: ‘constexpr’ does not name a type
   constexpr int32_t unsigned32ToSigned2sCompl(uint32_t x) {
   ^
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:34:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:38:1: error: ‘constexpr’ does not name a type
   constexpr int64_t unsigned64ToSigned2sCompl(uint64_t x) {
   ^
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:38:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:42:1: error: ‘constexpr’ does not name a type
   constexpr uint64_t signExtend2sCompl(uint32_t x) {
   ^
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:42:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:46:1: error: ‘constexpr’ does not name a type
   constexpr int RoundToNearest = 0;
   ^
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:46:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:47:1: error: ‘constexpr’ does not name a type
   constexpr int RoundDown = 1;
   ^
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:47:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:48:1: error: ‘constexpr’ does not name a type
   constexpr int RoundUp = 2;
   ^
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:48:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:49:1: error: ‘constexpr’ does not name a type
   constexpr int RoundToZero = 3;
   ^
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:49:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
  In file included from /root/kulupu/pow/randomx/sys/randomx/src/soft_aes.h:32:0,
                   from /root/kulupu/pow/randomx/sys/randomx/src/aes_hash.cpp:29:
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:166:1: error: ‘constexpr’ does not name a type
   constexpr uint32_t rx_mxcsr_default = 0x9FC0; //Flush to zero, denormals are zero, default rounding mode, all exceptions disabled
   ^
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:166:1: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
  In file included from /root/kulupu/pow/randomx/sys/randomx/src/soft_aes.h:32:0,
                   from /root/kulupu/pow/randomx/sys/randomx/src/aes_hash.cpp:29:
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h: In function ‘void rx_reset_float_state()’:
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:169:13: error: ‘rx_mxcsr_default’ was not declared in this scope
    _mm_setcsr(rx_mxcsr_default);
               ^
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h: In function ‘void rx_set_rounding_mode(uint32_t)’:
  /root/kulupu/pow/randomx/sys/randomx/src/intrin_portable.h:173:13: error: ‘rx_mxcsr_default’ was not declared in this scope
    _mm_setcsr(rx_mxcsr_default | (mode << 13));
               ^
  /root/kulupu/pow/randomx/sys/randomx/src/aes_hash.cpp: In function ‘void hashAndFillAes1Rx4(void*, size_t, void*, void*)’:
  /root/kulupu/pow/randomx/sys/randomx/src/aes_hash.cpp:264:2: error: ‘constexpr’ was not declared in this scope
    constexpr int PREFETCH_DISTANCE = 4096;
    ^
  /root/kulupu/pow/randomx/sys/randomx/src/aes_hash.cpp:264:12: error: expected ‘;’ before ‘int’
    constexpr int PREFETCH_DISTANCE = 4096;
              ^
  /root/kulupu/pow/randomx/sys/randomx/src/aes_hash.cpp:265:56: error: ‘PREFETCH_DISTANCE’ was not declared in this scope
    const char* prefetchPtr = ((const char*)scratchpad) + PREFETCH_DISTANCE;
                                                          ^
  gmake[2]: *** [CMakeFiles/randomx.dir/src/aes_hash.cpp.o] Error 1
  gmake[1]: *** [CMakeFiles/randomx.dir/all] Error 2
  gmake: *** [all] Error 2

  --- stderr
  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS

  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 2

  build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.44/src/lib.rs:885:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by JKinGH** [comment]
I have give up build and useing the [release binary](https://github.com/kulupu/kulupu/releases) to mining.
```
./kulupu generate-mining-key
./kulupu import-mining-key "your key"
./kulupu --validator --author 0x043f6098a90ba8f38597341879cd3bac8109a54069baedcd54e319d73d0a472e
```

**Comment by AMikrukov** [comment]
Having the same error under CentOS 7. The release binary doesn't work in my environment. Says "Segmentation fault (core dumped)".

**Comment by sorpaas** [comment]
Please use issue #71.
