### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by chywhy** [kulupu/kulupu#68]
`./kulupu --validator --author 0x5ec99020f459706ad83d4e56336b7967908f97b61985b6ef9a44b8879003c367`

error:
`INFO kulupu-randomx  At block boundary, generating new RandomX full cache with key hash 0xf7a9…69ba ...
Segmentation fault (core dumped)`

**Comment by sorpaas** [comment]
Duplicate. Please use issue #70.
