### ISSUE TITLE
Thread 'main' panicked at 'Invalid author address: BadBase58', src/service.rs:49

### ISSUE THREAD

**Issue by sodexx7** [kulupu/kulupu#72]
14: __libc_start_main
  15: _start

Thread 'main' panicked at 'Invalid author address: BadBase58', src/service.rs:49

**Comment by sorpaas** [comment]
That means you provided invalid author address. Make sure you followed the guide in generating the wallet address.

Use https://github.com/kulupu/kulupu/issues/70 to discuss further documentation issues of the mining guide.
