### ISSUE TITLE
After running kulupu.exe with bat file I get the following

### ISSUE THREAD

**Issue by sun7aster** [kulupu/kulupu#76]
You are using the peer ID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.

Not sure what this means or what I need to do here. The miner seems to run but no payments so far after 24 hours.

**Comment by sorpaas** [comment]
It's a warning that can be ignored. See https://kulupu.network/guide/mining/#warnings-that-can-be-ignored
