### ISSUE TITLE
How can I make multiple computers mining together?

### ISSUE THREAD

**Issue by oopos** [kulupu/kulupu#78]
I used a amd3900x computer to mining for 3 days, and I didn't mining any KLP coin. Why? 
How can I make multiple computers mining together?

**Comment by JulsKawa** [comment]
Because your computer haven't found the block

**Comment by Sepkuh** [comment]
Because difficulty is very high and it takes more then 2 days to find a block with a ryzen 9 3900x.

More computers will have the same hashrates. So you spread your chances, but they are not combined.

But you just enter the same address on every computer.

**Comment by Sepkuh** [comment]
And it's much easier to go to our discord channel and ask, then opening a github issue for this

**Comment by shawntabrizi** [comment]
Yes, @Sepkuh is correct. Set up multiple computers with the Kulupu node, and just run them each as miners.

Each of them will have their own chance to find the right block, but together, your chances are all added together.

If you use the same mining key on all the computers, you will get the reward into the same account no matter which computer is mining, but i would recommend to probably use different keys just to decrease the likelihood of your single key getting leaked.
