### ISSUE TITLE
mining bug

### ISSUE THREAD

**Issue by villagecryptomaster** [kulupu/kulupu#93]
D:\klp>.\start.bat

D:\klp>kulupu.exe --validator --author 2d*********************** --threads 4
[2mOct 01 16:28:54.684[0m [32m INFO[0m Kulupu
[2mOct 01 16:28:54.686[0m [32m INFO[0m ??  version 2.2.1-f77e9ee-x86_64-windows-msvc
[2mOct 01 16:28:54.687[0m [32m INFO[0m ??  by Wei Tang <wei@that.world>, 2019-2020
[2mOct 01 16:28:54.687[0m [32m INFO[0m ?? Chain specification: Kulupu
[2mOct 01 16:28:54.687[0m [32m INFO[0m ??  Node name: ill-fated-rod-4921
[2mOct 01 16:28:54.688[0m [32m INFO[0m ?? Role: AUTHORITY
[2mOct 01 16:28:54.688[0m [32m INFO[0m ?? Database: RocksDb at C:\Users\Administrator\AppData\Local\kulupu.exe\data\
chains\kulupu\db
[2mOct 01 16:28:54.688[0m [32m INFO[0m ?  Native runtime: kulupu-10 (kulupu-0.tx6.au5)
[2mOct 01 16:28:54.749[0m [32m INFO[0m ??  Local node identity is: 12D3KooWBdGTmKmya8JyhH8GFQtrxLSBmNTwxDYvM1iqKA4ia
kEB (legacy representation: 12D3KooWBdGTmKmya8JyhH8GFQtrxLSBmNTwxDYvM1iqKA4iakEB)

====================

Version: 2.2.1-f77e9ee-x86_64-windows-msvc

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: BaseThreadInitThunk
  23: RtlUserThreadStart

Thread 'main' panicked at 'UdpSocket is known to be good: Os { code: 10014, kind: Other, message: "系统检测到在一个调用
中尝试使用指针参数时的无效指针地址。" }', C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\asyn
c-std-1.6.3\src\net\udp\mod.rs:487

This is a bug. Please report it at:
-------------------------------------------------------------------------------------------------------------------------------------
Anyone have idea to fix this?

**Comment by OIEIEIO** [comment]
2020-11-27 17:33:51  🎁 Prepared block for proposing at 289192 [hash: 0x68bf9299cfde386b13622d108586f39f851c7e1883a1d1d985d606a3ce5e9b18; parent_hash: 0xa201…5508; extrinsics (2): [0xa915…8727, 0x7537…20ef]]    
2020-11-27 17:33:51  💤 Idle (8 peers), best: #289204 (0xf588…4304), finalized #0 (0xf7a9…69ba), ⬇ 2.1kiB/s ⬆ 1.8kiB/s    

====================

Version: 2.3.0-c99368a-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/panicking.rs:581:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: primitive_types::U256::div_mod
   6: kulupu_pow::mine
   7: kulupu::service::new_full::{{closure}}
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/sys/unix/thread.rs:89:17
  11: start_thread
  12: clone


Thread '<unnamed>' panicked at 'division by zero', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.7.2/src/lib.rs:32

This is a bug. Please report it at:

	https://github.com/kulupu/kulupu/issues

root@sub1:~/kulupu# 

My first crash

**Comment by OIEIEIO** [comment]
Mind you I am running inside LXC container - could be problem from my end

**Comment by OIEIEIO** [comment]
root@sub1:~/kulupu# grep Hugepagesize /proc/meminfo
Hugepagesize:       2048 kB
root@sub1:~/kulupu#

**Comment by OIEIEIO** [comment]
This problem resolved itself after a reboot. Chain running well now and mining with 10 threads

**Comment by OIEIEIO** [comment]
cargo run --release -- --validator --threads 10 --author 2ep3eJgJz

**Comment by sorpaas** [comment]
The UdpSocket one seems to be a system issue -- Internet disconnect or something.
The later one is fixed by https://github.com/kulupu/kulupu/pull/117

Let me know if the issue still persists.
