### ISSUE TITLE
Compiling failure

### ISSUE THREAD

**Issue by tukai800** [kulupu/kulupu#95]
SW version：2.3.0
OS：ubuntu-20.04.1-live-server-amd64 / ubuntu-18.04.5-live-server-amd64

compiled successful almost 778 files of 825 then the error appeared.

=========================================================
log segment:

myhome@myhome:~/kulupu$ cargo run --release
…………
      Compiling frame-metadata v12.0.0 (/home/myhome/kulupu/vendor/substrate/frame/metadata)
  error[E0282]: type annotations needed
      --> /home/myhome/kulupu/vendor/substrate/primitives/arithmetic/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1595 | / implement_fixed!(
  1596 | |     FixedI64,
  1597 | |     test_fixed_i64,
  1598 | |     i64,
  ...    |
  1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
  1602 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error[E0282]: type annotations needed
      --> /home/myhome/kulupu/vendor/substrate/primitives/arithmetic/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1604 | / implement_fixed!(
  1605 | |     FixedI128,
  1606 | |     test_fixed_i128,
  1607 | |     i128,
  ...    |
  1611 | |         [-170141183460469231731.687303715884105728, 170141183460469231731.687303715884105727]_",
  1612 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error[E0282]: type annotations needed
      --> /home/myhome/kulupu/vendor/substrate/primitives/arithmetic/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1614 | / implement_fixed!(
  1615 | |     FixedU128,
  1616 | |     test_fixed_u128,
  1617 | |     u128,
  ...    |
  1621 | |         [0.000000000000000000, 340282366920938463463.374607431768211455]_",
  1622 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: aborting due to 3 previous errors

  For more information about this error, try `rustc --explain E0282`.
  error: could not compile `sp-arithmetic`

  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
warning: build failed, waiting for other jobs to finish...
error: build failed

What should I do next ? Thank you!

**Comment by sgaragagghu** [comment]
[](https://github.com/substrate-developer-hub/substrate-node-template/pull/91/files)

**Comment by tukai800** [comment]
@sgaragagghu Thank you very much ! I will have a try just now!

**Comment by tukai800** [comment]
I've followed the new Instruction, but the  error still.

**Comment by sgaragagghu** [comment]
`rustup default nightly-2020-10-06-x86_64-unknown-linux-gnu`

**Comment by sorpaas** [comment]
Update Rust version will fix this issue.
